services:
  mysqldb:
    image: mysql:8.0.22
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullstack-starter-network

  my-service:
    container_name: my-service
    build:
      context: .
      dockerfile: DockerfileWithDependency
      args:
        DEPENDENCY: auth-api
        SERVICE: my-service
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      - fullstack-starter-network
    restart: on-failure
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/my-service?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SERVICES_AUTH_BASE_URL: http://auth-service:8080

volumes:
  mysql-data:

networks:
  fullstack-starter-network: