services:
  mysqldb:
    image: mysql:8.0.22
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-boot-mysql-network

  spring-boot-auth:
    container_name: fullstack-starter-auth
    build:
      context: .
      args:
        SERVICE: auth
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      - spring-boot-mysql-network
    restart: on-failure

  spring-boot-my-service:
    container_name: fullstack-starter-my-service
    build:
      context: .
      args:
        SERVICE: my-service
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      - spring-boot-mysql-network
    restart: on-failure
    environment:
      spring.datasource.username: root
      spring.datasource.password: password
      spring.datasource.url: jdbc:mysql://mysqldb:3306/my-service?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true

volumes:
  mysql-data:

networks:
  spring-boot-mysql-network: